name: caller terraform plan workflow (dev)
on:
  # pull_request:
  #   branches:
  #     - main
  #   paths:
  #     - 'terraform/dev/**'
  #   types:
  #     - opened
  #     - synchronize

  # test用
  push:
    branches:
      - develop

jobs:
  call_workflow:
    # uses: y-tsuritani/Slackbot_ChatGPT.git/.github/workflows/_tf_plan.yml@main
    # test用
    uses: y-tsuritani/github-actions-via-wlif/.github/workflows/_tf_plan.yml@develop
    with:
      SLACK_MESSAGE_TARGET_ENV: dev
      TF_VERSION: 1.3.4
      TF_WORK_DIR: terraform/dev
    secrets:
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.DEV_WORKLOAD_IDENTITY_PROVIDER }}
      SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
